### ISSUE TITLE
`npx ota validate` reports an InaccessibleContentError

### ISSUE THREAD

**Issue by michielbdejong** [OpenTermsArchive/engine#1100]
I followed the instructions on https://docs.opentermsarchive.org/ and 
```
npx ota track --services "Open Terms Archive" --types "Privacy Policy"
```
works, but
```
npx ota validate --services "Open Terms Archive" --types "Privacy Policy"
```
fails with the following output:
```
Service declarations validation
    Open Terms Archive
      ✔ valid declaration schema
      Privacy Policy
        https://opentermsarchive.org/en/privacy-policy
          ✔ fetchable URL
          1) selector matches an element in the source document
          [Tests skipped as content cannot be filtered]
          - filtered content has at least 100 characters
          [Tests skipped as content cannot be filtered]
          - content is consistent when fetched and filtered twice in a row


  2 passing (722ms)
  2 pending
  1 failing

  1) Service declarations validation
       Open Terms Archive
         Privacy Policy
           https://opentermsarchive.org/en/privacy-policy
             selector matches an element in the source document:
     InaccessibleContentError: The documents cannot be accessed or their contents can not be selected:
 - The provided selector ".TextContent_textContent__ToW2S" has no match in the web page at 'https://opentermsarchive.org/en/privacy-policy'
      at extractFromHTML (file:///Users/michiel/gh/tosdr/tosdr-declarations/node_modules/@opentermsarchive/engine/src/archivist/extract/index.js:75:11)
      at extract (file:///Users/michiel/gh/tosdr/tosdr-declarations/node_modules/@opentermsarchive/engine/src/archivist/extract/index.js:36:10)
      at Context.checkSelector (file:///Users/michiel/gh/tosdr/tosdr-declarations/node_modules/@opentermsarchive/engine/scripts/declarations/validate/index.mocha.js:127:47)
      at process.processImmediate (node:internal/timers:478:21)
```

It seems to work when I change [the selector in the documented example](https://github.com/OpenTermsArchive/docs/blob/7c1f9c0c664f5fddf7133bc869cdc6058cae3b64/content/_index.en.md?plain=1#L129) from `".TextContent_textContent__ToW2S"` to `".textcontent"`

Maybe the reason that `npx ota track` did not report the same error as `npx ota validate` is that it doesn't have the `"selector matches an element in the source document"` test?

**Comment by clementbiron** [comment]
Hi Michiel !

We consider that the process should not stop if the selectors no longer work, which is why `track` works and `validate` failed. This is a bit of a short answer, so don't hesitate to ask me for more details if you need them.

Thank you for pointing out the error in the documentation, it's true that the selector isn't the right one! I made a correction in this [pull request](https://github.com/OpenTermsArchive/docs/pull/141).
